os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)"
script:
  # run unit tests
  - swift build
  - swift build --configuration release
  - swift test

  - .build/release/Executable self install
  - vapor version                   # version

  # docker
  # - rm Dockerfile                   # docker init won't run if file exists
  # - vapor docker init

  # heroku
  # - vapor heroku init

  # basic
  - vapor help                      # help
  - vapor new test-project          # new
  - cd test-project
  - vapor clean                     # clean
  - vapor build                     # build
  - vapor run &                     # run

  # test update
  # FIXME: enable later - this can only work after cli.qutheory.io starts serving bootstrap.swift
  #- vapor update                    # will update to older version
