os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode7.3
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)"
script:
  - ./vapor.swift self compile      # compile
  - sudo mv ./vapor /usr/local/bin/ # install

  - ./vapor.swift self update       # self-update, will overwrite `./vapor.swift`
                                    # which we'll ignore

  # docker
  - vapor docker init

  # heroku
  # - vapor heroku init

  # basic
  - vapor help                      # help
  - vapor new test-project          # new
  - cd test-project
  - vapor clean                     # clean
  - vapor build                     # build
  - vapor run &                     # run
  