name: 'Vapor'
description: 'Vapor Toolbox'
inputs:
  command:
    description: 'Command to run'
    required: true
    default: '--help'
runs:
  using: 'docker'
  image: 'docker://vapor/toolbox:18'
  entrypoint: sh -c "vapor $*"
  args:
    - ${{ inputs.command }}
