version: 2

jobs:
  macos:
    macos:
      xcode: "9.3"
    steps:
      - checkout
      - run: swift build
      - run: swift test

  linux:
    docker:
      - image: codevapor/swift:4.1
    steps:
      - checkout
      - run: 
          name: Compile code
          command: swift build -Xswiftc -DNO_ANIMATION
      - run: 
          name: Run unit tests
          command: swift test
      - run: 
          name: Compile code with optimizations
          command: swift build -c release -Xswiftc -DNO_ANIMATION
      - run:
          name: Run Vapor commands
          command: |
            mv .build/release/Executable /usr/local/bin/vapor
            vapor --help
            vapor version

workflows:
  version: 2
  tests:
    jobs:
      - linux
      - macos
